# Generated by Django 3.1.7 on 2021-04-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(max_length=150)),
                ('latitude', models.FloatField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('address', models.CharField(default=True, max_length=150)),
                ('coordinate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy_Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField(unique=True)),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.drug')),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(default=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('password', models.CharField(default=False, max_length=150)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.drug')),
                ('pharmacy_drug_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pharmacy_drug', to_field='price')),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.user'),
        ),
        migrations.CreateModel(
            name='Favourite_Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.pharmacy')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.drug')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
